### ISSUE TITLE
Matrix Error

### ISSUE THREAD

**Issue by ajgreen1987** [farice/ARShooter#11]
Just forked and receiving:

Cannot invoke initializer for type 'SCNMatrix4' with an argument list of type '(matrix_float4x4)'

Played around a bit with manual init, but not keen on extracting and typing the variables.

**Comment by rafus15** [comment]
Having the same problem here, cannot fix it i'm a little lost with arkit still

**Comment by rafus15** [comment]
Fixed it!
You just need to update to Xcode 9 Beta 2 and the problem is solved!
Hope it helps

**Comment by ajgreen1987** [comment]
Perfect! I actually started the download last night hoping that would be the case but ended up needing sleep before it was finished. Thanks!

**Comment by farice** [comment]
Duplicate of https://github.com/farice/ARShooter/issues/7 and https://github.com/farice/ARShooter/issues/8

I'll add this to the FAQ in the README.
