### ISSUE TITLE
Camera Transform Matrix Values

### ISSUE THREAD

**Issue by hmerzin** [farice/ARShooter#14]
Hi, I was looking for ways to implement projectiles in my ARKit project and stumbled across your ViewController. I saw that in the method `getUserVector`,  the direction property was set based on positions: m31, 32, and 33 of the camera transform matrix and I was wondering how you figured this out. I wasn't able to find it anywhere I looked in any documentation, article or video. Is there some sort of documentation on the properties of this matrix you found? Sorry to open a new issue. I hope I'm not bugging you, I was just insanely curious about that one line (which helped me a lot, thank you!).

Cheers, Harry

**Comment by farice** [comment]
I did not see this in the documentation!

I determined it myself by considering the linear algebra at hand. I'll update with more details on the website (texnotes.me) soon and then I'll link you. Glad I was able to help.

Cheers,
Faris

**Comment by hmerzin** [comment]
Thanks so much!

-harry
