### ISSUE TITLE
iPhone5s crash 

### ISSUE THREAD

**Issue by TeacherXue** [farice/ARShooter#2]
2017-06-07 18:40:19.329904+0800 ARViewer[771:115352] -[MTLTextureDescriptorInternal validateWithDevice:], line 778: error 'MTLTextureDescriptor has invalid pixelFormat (520).'
-[MTLTextureDescriptorInternal validateWithDevice:]:778: failed assertion `MTLTextureDescriptor has invalid pixelFormat (520).'

on  iPhone5s , but iPhone5s simulator is ok

**Comment by farice** [comment]
@TeacherXue What does your console output look like? Can you also pull before you test again, because I just added more debug output in the latest commit?

**Comment by farice** [comment]
Just found the problem in [the current iOS 11 beta release notes](https://beta.applebetas.co/notes/ios/11/beta1.pdf).

<img width="624" alt="screen shot 2017-06-07 at 7 24 33 am" src="https://user-images.githubusercontent.com/13244177/26883570-6a178a18-4b52-11e7-913c-489993619a54.png">

Looks like you'll have to wait until a later beta release :( iPhone 6S+ have A9+ chips.

The good news is, ARSessionConfiguration will be supported for your device some time soon. They did a poor job of documenting this (on their webpage they claim that all devices support this configuration but fail to mention that the current beta release doesn't implement such inclusive behavior yet).

**Comment by TeacherXue** [comment]
oh, ok  thank u  for ur answer
