### ISSUE TITLE
sound effects enhancement

### ISSUE THREAD

**Issue by wave-electron** [farice/ARShooter#5]
A simple enhancement is adding sound effects using AVFoundation. I added 3 basic sound effects, torpedo.mp3 (bullet sound), explosion.mp3 , collison.mp3. 

sound effects available: 
[torpedo.mp3](http://www.trekcore.com/audio/weapons/tng_torpedo3_clean.mp3)
[explosion.mp3](https://www.freesoundeffects.com/free-sounds/bomb-10076/)
[collision.mp3](http://soundbible.com/996-Kick.html)

import AVFoundation
var Player: AVAudioPlayer = AVAudioPlayer()

```

// added this basic code snippet in three places just change the forResource for each mp3 name.
do
        {
           let MusicURL = Bundle.main.path(forResource: "torpedo", ofType: "mp3")
            try Player = AVAudioPlayer(contentsOf: NSURL (fileURLWithPath:MusicURL!) as URL)
            Player.prepareToPlay()
           Player.play()
        }
        catch let error as NSError {
           print(error.description)
       }
```

1st spot.  after  

```
@IBAction func didTapScreen(_ sender: UITapGestureRecognizer) { // fire bullet in direction camera is facing
```

2nd spot.  after 
```

 func removeNodeWithAnimation(_ node: SCNNode, explosion: Bool) {
        
        
        if explosion {

```

3rd spot after

```
 func physicsWorld(_ world: SCNPhysicsWorld, didBegin contact: SCNPhysicsContact) {
        //print("did begin contact", contact.nodeA.physicsBody!.categoryBitMask, contact.nodeB.physicsBody!.categoryBitMask)
        if contact.nodeA.physicsBody?.categoryBitMask == CollisionCategory.ship.rawValue || contact.nodeB.physicsBody?.categoryBitMask == CollisionCategory.ship.rawValue { // this conditional is not required--we've used the bit masks to ensure only one type of collision takes place--will be necessary as soon as more collisions are created/enabled
            do
            {

```

Thats it!

**Comment by farice** [comment]
Sound effects would be cool! Could I ask you to submit a pull request with this included?

**Comment by wave-electron** [comment]
@farice 

I'm just in the process of downloading Xcode 9 beta 2. Will look at it tomorrow for you. 

This is a video of the game with sound effects
[video](https://www.facebook.com/ashley.joyce.3304/videos/10155559100563939/?permPage=1)

**Comment by farice** [comment]
Very nice! @wave-electron

**Comment by farice** [comment]
Merged https://github.com/farice/ARShooter/pull/10
