### ISSUE TITLE
Open the project，Prompt bug:Cannot invoke initializer for type 'SCNMatrix4' with an argument list of type '(matrix_float4x4)'

### ISSUE THREAD

**Issue by wangyi1998** [farice/ARShooter#8]
Open the project，
Prompt bug:Cannot invoke initializer for type 'SCNMatrix4' with an argument list of type '(matrix_float4x4)'...
Can you see?A great god

**Comment by anaz-jaleel** [comment]
replace SCNMatrix4 with SCNMatrix4FromMat4

**Comment by farice** [comment]
See https://github.com/farice/ARShooter/issues/7

If you insist on using the first Xcode beta then simply follow the recommendation of @AIMLAR. I'd recommend updating to the [latest beta](https://developer.apple.com/download/) though.
