### ISSUE TITLE
Remove old "bullets"

### ISSUE THREAD

**Issue by schenkty** [farice/ARShooter#9]
Is there a way to remove old bullet nodes? I have been looking around the project and can't seem to figure out how to do it. Without this functionality, there are a bunch of "bullets" flying around.

**Comment by farice** [comment]
There are a few ways to do this. The simplest is to use the `DispatchQueue` to remove the node asynchronously on the main thread at some future time.

At the bottom of the `didTapScreen` method in `ViewController.swift` add the following block

        DispatchQueue.main.asyncAfter(deadline: .now() + 10, execute: {
            print("removing bullet")
            self.removeNodeWithAnimation(bulletsNode, explosion: false)
        })

Replace 10 with how many seconds you'd like the bullets to disappear after.

**Comment by farice** [comment]
Alternatively, checkout the [bullets-disappear](https://github.com/farice/ARShooter/tree/bullets-disappear) branch I just pushed up.

**Comment by schenkty** [comment]
Perfect! To be honest with you, I blanked on that being a way to do it. Thank you
